#define OS_LINUX	1
#define ARCH_X86_64	1
#define C_GCC	1
#define __64BIT__	1
#define PTHREAD_CREATE_FUNC	pthread_create
#define BUNDERSCORE _
#define NEEDBUNDERSCORE 1
#define ZEN
#define L1_CODE_SIZE 32768
#define L1_CODE_LINESIZE 64
#define L1_CODE_ASSOCIATIVE 8
#define L1_DATA_SIZE 32768
#define L1_DATA_LINESIZE 64
#define L2_CODE_ASSOCIATIVE 8
#define L2_SIZE 524288
#define L2_LINESIZE 64
#define L2_ASSOCIATIVE 8
#define L3_SIZE 16777216
#define L3_LINESIZE 64
#define L3_ASSOCIATIVE 8
#define ITB_DEFAULT_ENTRIES 64
#define ITB_SIZE 4096
#define DTB_DEFAULT_ENTRIES 64
#define DTB_SIZE 4096
#define HAVE_MMX
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_SSE3
#define HAVE_SSE4_1
#define HAVE_SSE4_2
#define HAVE_SSE4A
#define HAVE_MISALIGNSSE
#define HAVE_128BITFPU
#define HAVE_FASTMOVU
#define HAVE_CFLUSH
#define HAVE_AVX
#define HAVE_FMA3
#define FMA3
#define CORE_ZEN
#define CHAR_CORENAME "ZEN"
#define SLOCAL_BUFFER_SIZE	24576
#define DLOCAL_BUFFER_SIZE	32768
#define CLOCAL_BUFFER_SIZE	12288
#define ZLOCAL_BUFFER_SIZE	8192
#define GEMM_MULTITHREAD_THRESHOLD	4
