#define ARCH_X86_64	1
#define C_GCC	1
#define __64BIT__	1
#define PTHREAD_CREATE_FUNC	pthread_create
#define BUNDERSCORE _
#define NEEDBUNDERSCORE 1
#define SANDYBRIDGE
#define L1_DATA_SIZE 32768
#define L1_DATA_LINESIZE 64
#define L2_SIZE 262144
#define L2_LINESIZE 64
#define DTB_DEFAULT_ENTRIES 64
#define DTB_SIZE 4096
#define HAVE_CMOV
#define HAVE_MMX
#define HAVE_SSE
#define HAVE_SSE2
#define HAVE_SSE3
#define HAVE_SSSE3
#define HAVE_SSE4_1
#define HAVE_SSE4_2
#define HAVE_AVX
#define CORE_SANDYBRIDGE
#define CHAR_CORENAME "SANDYBRIDGE"
#define SLOCAL_BUFFER_SIZE	24576
#define DLOCAL_BUFFER_SIZE	16384
#define CLOCAL_BUFFER_SIZE	32768
#define ZLOCAL_BUFFER_SIZE	24576
#define GEMM_MULTITHREAD_THRESHOLD	4
