name: Explosion Bot

on:
  issue_comment:
    types:
      - created
      - edited

permissions: {}

jobs:
  explosion-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      - name: Install and run explosion-bot
        run: |
          git config --global url."https://x-access-token:${EXPLOSIONBOT_TOKEN}@github.com/".insteadOf "https://github.com/"
          pip install git+https://github.com/explosion/explosion-bot@da93b7c284cc002c63218de7e0e82610e47ced91
          python -m explosionbot
        env:
          EXPLOSIONBOT_TOKEN: ${{ secrets.EXPLOSIONBOT_TOKEN }}
          INPUT_TOKEN: ${{ secrets.EXPLOSIONBOT_TOKEN }}
          INPUT_BK_TOKEN: ${{ secrets.BUILDKITE_SECRET }}
          ENABLED_COMMANDS: "test_gpu,test_slow,test_slow_gpu"
          ALLOWED_TEAMS: "spacy-maintainers"
